/// One source or target namespace selected for native schema comparison.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct SchemaDiffEndpoint {
    pub(crate) datasource_id: String,
    pub(crate) database_name: String,
    pub(crate) schema_name: String,
}

/// Desired source and migration target for native schema comparison.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct SchemaDiffRequest {
    pub(crate) source: SchemaDiffEndpoint,
    pub(crate) target: SchemaDiffEndpoint,
}

/// SQL generated by a native schema-comparison capability.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct SchemaDiffSql(String);

impl SchemaDiffSql {
    pub(crate) fn new(sql: impl Into<String>) -> Self {
        Self(sql.into())
    }

    pub(crate) fn into_inner(self) -> String {
        self.0
    }
}
