use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// One JDBC driver declaration retained from a Community plugin.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct CommunityDriverConfig {
    /// JDBC URL template declared by the plugin.
    pub url: String,
    /// Driver artifact name declared by Community.
    pub jdbc_driver: String,
    /// JDBC driver implementation class.
    pub jdbc_driver_class: String,
    /// Ordered upstream download locations declared by Community.
    pub download_urls: Vec<String>,
    /// Whether this is a user-supplied driver declaration.
    pub custom: bool,
    /// Whether this is the plugin's default driver declaration.
    pub default_driver: bool,
}

/// Database-model and script behavior declared by one Community plugin.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct CommunityPluginBehavior {
    /// Whether the plugin models databases as metadata containers.
    pub supports_database: bool,
    /// Whether the plugin models schemas as metadata containers.
    pub supports_schema: bool,
    /// Whether the plugin preserves script batches during execution.
    pub preserves_script_batch_execution: bool,
}

/// Optional Community services exposed by one plugin.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct CommunityPluginServices {
    /// Whether schema metadata is available.
    pub metadata_available: bool,
    /// Whether dialect SQL building is available.
    pub sql_builder_available: bool,
    /// Whether retained SQL parsing is available.
    pub sql_parser_available: bool,
}

/// Stable product projection of one Community plugin.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct CommunityPlugin {
    /// Community database type used to select the plugin.
    pub database_type: String,
    /// User-visible plugin name.
    pub name: String,
    /// Database-model and script behavior.
    pub behavior: CommunityPluginBehavior,
    /// JDBC driver declarations in Community order.
    pub drivers: Vec<CommunityDriverConfig>,
    /// Optional retained Community services.
    pub services: CommunityPluginServices,
}

/// Community plugin inventory for one fixed source commit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct CommunityPluginCatalog {
    /// Full source commit backing the compatibility classpath.
    pub source_commit: String,
    /// Plugins in deterministic discovery order.
    pub plugins: Vec<CommunityPlugin>,
}

/// Secret-free database schema metadata returned by Community.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct CommunitySchema {
    /// Database containing the schema.
    pub database_name: String,
    /// Schema name.
    pub name: String,
    /// Schema comment when supplied by the database.
    pub comment: String,
    /// Schema owner when supplied by the database.
    pub owner: String,
    /// Whether Community classifies the schema as system-owned.
    pub system: bool,
}

/// Stable schema collection returned by Community metadata APIs.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct CommunitySchemaList {
    /// Schemas in compatibility-engine order.
    pub items: Vec<CommunitySchema>,
}

/// Request to list schemas through one datasource connection.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ListCommunitySchemasRequest {
    /// Datasource whose installed connection descriptor is used.
    pub datasource_id: String,
    /// Community database type used to select the metadata plugin.
    pub database_type: String,
    /// Database name supplied to Community metadata.
    pub database_name: String,
}

/// Request to build dialect-specific `CREATE SCHEMA` SQL.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct BuildCommunityCreateSchemaRequest {
    /// Community database type used to select the SQL builder.
    pub database_type: String,
    /// Schema description passed to the retained builder.
    pub schema: CommunitySchema,
}

/// SQL built by a retained Community dialect service.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct CommunityBuiltSql {
    /// Complete SQL generated by Community.
    pub sql: String,
}

/// Request to analyze SQL through a retained Community parser.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct ParseCommunitySqlRequest {
    /// Community database type used to select the parser.
    pub database_type: String,
    /// SQL text to analyze.
    pub sql: String,
}

/// One statement returned by the retained Community parser.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct CommunityParsedStatement {
    /// Statement SQL projected by Community.
    pub sql: String,
    /// Community statement type.
    pub statement_type: String,
    /// Bounded parser-specific statement kind.
    pub kind: String,
}

/// Bounded Community parser projection for one SQL input.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct CommunitySqlAnalysis {
    /// Whether Community classifies the complete input as a select operation.
    pub is_select: bool,
    /// Parsed statements in source order.
    pub statements: Vec<CommunityParsedStatement>,
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{
        BuildCommunityCreateSchemaRequest, CommunityBuiltSql, CommunityDriverConfig,
        CommunityParsedStatement, CommunityPlugin, CommunityPluginBehavior, CommunityPluginCatalog,
        CommunityPluginServices, CommunitySchema, CommunitySchemaList, CommunitySqlAnalysis,
        ListCommunitySchemasRequest, ParseCommunitySqlRequest,
    };

    #[test]
    fn community_contracts_use_exact_camel_case_json() {
        let catalog = CommunityPluginCatalog {
            source_commit: "f63cbf4".to_owned(),
            plugins: vec![CommunityPlugin {
                database_type: "H2".to_owned(),
                name: "H2".to_owned(),
                behavior: CommunityPluginBehavior {
                    supports_database: true,
                    supports_schema: true,
                    preserves_script_batch_execution: false,
                },
                drivers: vec![CommunityDriverConfig {
                    url: "jdbc:h2:mem:test".to_owned(),
                    jdbc_driver: "h2.jar".to_owned(),
                    jdbc_driver_class: "org.h2.Driver".to_owned(),
                    download_urls: vec!["https://example.invalid/h2.jar".to_owned()],
                    custom: false,
                    default_driver: true,
                }],
                services: CommunityPluginServices {
                    metadata_available: true,
                    sql_builder_available: true,
                    sql_parser_available: true,
                },
            }],
        };

        let value = serde_json::to_value(&catalog).expect("catalog must serialize");
        assert_eq!(value["sourceCommit"], "f63cbf4");
        assert_eq!(value["plugins"][0]["databaseType"], "H2");
        assert_eq!(value["plugins"][0]["behavior"]["supportsSchema"], true);
        assert_eq!(
            value["plugins"][0]["behavior"]["preservesScriptBatchExecution"],
            false
        );
        assert_eq!(
            value["plugins"][0]["drivers"][0]["jdbcDriverClass"],
            "org.h2.Driver"
        );
        assert_eq!(value["plugins"][0]["services"]["sqlParserAvailable"], true);
        assert_eq!(
            serde_json::from_value::<CommunityPluginCatalog>(value)
                .expect("catalog must deserialize"),
            catalog
        );
    }

    #[test]
    fn community_requests_and_responses_round_trip() {
        let schema = CommunitySchema {
            database_name: "inventory".to_owned(),
            name: "reporting".to_owned(),
            comment: "Reporting objects".to_owned(),
            owner: "app".to_owned(),
            system: false,
        };
        let list_request = ListCommunitySchemasRequest {
            datasource_id: "datasource-1".to_owned(),
            database_type: "H2".to_owned(),
            database_name: "inventory".to_owned(),
        };
        let build_request = BuildCommunityCreateSchemaRequest {
            database_type: "H2".to_owned(),
            schema: schema.clone(),
        };
        let parse_request = ParseCommunitySqlRequest {
            database_type: "H2".to_owned(),
            sql: "select 1".to_owned(),
        };
        let schema_list = CommunitySchemaList {
            items: vec![schema],
        };
        let built = CommunityBuiltSql {
            sql: "CREATE SCHEMA reporting".to_owned(),
        };
        let analysis = CommunitySqlAnalysis {
            is_select: true,
            statements: vec![CommunityParsedStatement {
                sql: "select 1".to_owned(),
                statement_type: "SELECT".to_owned(),
                kind: "Select".to_owned(),
            }],
        };

        assert_eq!(
            serde_json::to_value(&list_request).expect("request must serialize"),
            json!({
                "datasourceId": "datasource-1",
                "databaseType": "H2",
                "databaseName": "inventory"
            })
        );
        assert_round_trip(&build_request);
        assert_round_trip(&parse_request);
        assert_round_trip(&schema_list);
        assert_round_trip(&built);
        assert_round_trip(&analysis);
    }

    #[test]
    fn community_metadata_contracts_never_expose_connection_secrets() {
        let response = CommunitySchemaList {
            items: vec![CommunitySchema {
                database_name: "inventory".to_owned(),
                name: "public".to_owned(),
                comment: String::new(),
                owner: "app".to_owned(),
                system: false,
            }],
        };

        let encoded = serde_json::to_string(&response).expect("schema list must serialize");
        for forbidden in [
            "\"connection\"",
            "\"jdbcUrl\"",
            "\"password\"",
            "\"properties\"",
            "\"secretRef\"",
        ] {
            assert!(!encoded.contains(forbidden), "response leaked {forbidden}");
        }
    }

    fn assert_round_trip<T>(value: &T)
    where
        T: std::fmt::Debug + PartialEq + serde::Serialize + serde::de::DeserializeOwned,
    {
        let encoded = serde_json::to_value(value).expect("contract must serialize");
        let decoded = serde_json::from_value::<T>(encoded).expect("contract must deserialize");
        assert_eq!(&decoded, value);
    }
}
